name: "✨ Feature"
description: New feature or enhancement
title: "[✨Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: What this feature aims to achieve
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      placeholder: "As a [role], I want [action], so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
